{"record_format_version": 3, "code": "\n        docker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev         /opt/conda/envs/pydev/bin/python {scripts}/validation_error_rates.py         --input {input[0]}         --stats-output {output[0]}         --plot-output {output[1]}\n        ", "rule": "validation_error_analysis", "input": ["output/C4H8O3_results.csv"], "log": [], "params": [], "shellcmd": "\n        docker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev         /opt/conda/envs/pydev/bin/python scripts/validation_error_rates.py         --input output/C4H8O3_results.csv         --stats-output output/C4H8O3_validation_error_stats.csv         --plot-output output/C4H8O3_validation_error_visualization.png\n        ", "incomplete": false, "starttime": 1734288245.629551, "endtime": 1734288246.8425844, "job_hash": 8728498515663, "conda_env": null, "container_img_url": null, "input_checksums": {"output/C4H8O3_results.csv": "1132d4331e401603a3106cf634129b7598c08a2b7e3088d5317c5e1ec900de53"}}