{"record_format_version": 3, "code": "\n        docker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev         /opt/conda/envs/pydev/bin/python {scripts}/validation_error_rates.py         --input {input[0]}         --stats-output {output[0]}         --plot-output {output[1]}\n        ", "rule": "validation_error_analysis", "input": ["output/C9H8O4_results.csv"], "log": [], "params": [], "shellcmd": "\n        docker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev         /opt/conda/envs/pydev/bin/python scripts/validation_error_rates.py         --input output/C9H8O4_results.csv         --stats-output output/C9H8O4_validation_error_stats.csv         --plot-output output/C9H8O4_validation_error_visualization.png\n        ", "incomplete": false, "starttime": 1734288256.8508613, "endtime": 1734288257.9648921, "job_hash": 8728498515935, "conda_env": null, "container_img_url": null, "input_checksums": {}}