{"record_format_version": 3, "code": "\n        docker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev         /opt/conda/envs/pydev/bin/python scripts/validation_error_rates.py         --input {input} --stats-output {output[0]} --plot-output {output[1]}\n        ", "rule": "validate_error_rates", "input": ["output/lipinski_results_with_fragments_20241204_095635.csv"], "log": [], "params": [], "shellcmd": "\n        docker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev         /opt/conda/envs/pydev/bin/python scripts/validation_error_rates.py         --input output/lipinski_results_with_fragments_20241204_095635.csv --stats-output output/validation_error_stats_20241204_095635.csv --plot-output output/validation_error_visualization_20241204_095635.png\n        ", "incomplete": false, "starttime": 1733302700.607235, "endtime": 1733302701.6542594, "job_hash": 8777933042965, "conda_env": null, "container_img_url": null, "input_checksums": {}}